# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'

variables:
  dockerRegistryServiceConnection: 'DockerHub'  # Name of your Docker Hub service connection
  imageName: 'revvver/mywebazure'  # Replace with your Docker Hub image name

jobs:
- job: Build
  displayName: 'Build Docker Image'
  steps:
  - checkout: self  # Checkout the code from the GitHub repository
  - task: Docker@2
    displayName: 'Build and Push Docker Image'
    inputs:
      command: 'buildAndPush'
      repository: '$(imageName)'
      dockerfile: '**/Dockerfile'  # Path to your Dockerfile
      containerRegistry: '$(dockerRegistryServiceConnection)'
      tags: |
        $(Build.BuildId)  # Tag the image with the build ID
