# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main  # Change this to your default branch

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: Build
  displayName: 'Build Job'
  steps:
  - script: echo Building the application...
    displayName: 'Build Step'

- job: Test
  displayName: 'Test Job'
  dependsOn: Build  # This job will run after the Build job
  steps:
  - script: echo Running tests...
    displayName: 'Test Step'

- job: Deploy
  displayName: 'Deploy Job'
  dependsOn: Test  # This job will run after the Test job
  steps:
  - script: echo Deploying the application...
    displayName: 'Deploy Step'

